name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r * ubuntu@13.60.99.60:~/your_app/

      - name: Install dependencies and restart app
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.99.60 << 'EOF'
            cd /var/www/your_app/
            # Install dependencies (adjust command based on your stack)
            npm install
            # Restart application (adjust command based on your process manager)
            pm2 restart all
          EOF
